### ISSUE TITLE
文档描述与values.yaml不一致

### ISSUE THREAD

**Issue by YiuTerran** [loggie-io/installation#36]
values.yaml中默认的config.discovery里面的字段，与[这里](https://loggie-io.github.io/docs/main/reference/global/discovery/#kubernetes)给出的默认值，不太一致啊。

**Comment by ethfoo** [comment]
具体是哪个不一样呢？values.yml里不一定是用的默认值

**Comment by YiuTerran** [comment]
那我觉得这个应该是个描述问题，就是如果用helm安装什么都不配置的话，理论上应该和文档中的默认值一致。

现在相当于程序里面有个默认值，values里面又覆盖掉了。

**Comment by ethfoo** [comment]
比如typePodFields字段，本身是一个map，没有默认值的，用户可以任意配置，为了快速上手，helm chart里给出了几个推荐的值。
containerRuntime这个当前values里写的是containerd，后面会改成默认空值，让Loggie自动识别，之前一直没有改是因为自动识别这个功能是后加的，会等该功能稳定后改掉。
其他值我看应该都是默认值吧，不知道你具体指的是哪个呢？

**Comment by YiuTerran** [comment]
主要就是这两个吧：
`.config.loggie.discovery.enabled`默认值写的是false，但是实际是true;
还有就是你说的那个，文档里面containerRuntime默认是docker, 但是实际上是containerd;

影响不大，不过有空可以改一下。

**Comment by ethfoo** [comment]
> `.config.loggie.discovery.enabled`默认值写的是false，但是实际是true;

默认是false，因为loggie默认不应该开启k8s的服务发现。values里是true因为helm chart部署到K8s里正常肯定是要开启的。
